### ISSUE TITLE
the problem about fastboot flash boot boot.img for pixel 2 xl

### ISSUE THREAD

**Issue by llllIIIllll** [nathanchance/pixel2-manifest#3]
hello.i complied the android 8.1-r1 and kernel-4.4.when i tried to run "fastboot flash boot boot.img",it shows Sending 'boot_b' (40960 KB)                        FAILED (remote: unknown command)
please help me how to solve it.

> my bootloader version is tmz12a
> baseband version g8998-00164-1710262031
> serial number - 710KPCA0244667

compile aosp and fastboot flashall -w ,it shows 

> target reported max download size of 536870912 bytes
> wiping userdata...
> mke2fs 1.43.3 (04-Sep-2016)
> 
> Warning: RAID stripe-width 1 not an even multiple of stride 2.
> 
> Creating filesystem with 13902843 4k blocks and 3481600 inodes
> Filesystem UUID: e8137926-c3cb-4ddc-bdd1-311c79ed416c
> Superblock backups stored on blocks: 
> 	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
> 	4096000, 7962624, 11239424
> 
> Allocating group tables: done                            
> Writing inode tables: done                            
> Creating journal (65536 blocks): done
> Writing superblocks and filesystem accounting information: done   
> 
> 
> Bootloader Version.: TMZ12a
> Baseband Version.....: g8998-00164-1710262031
> Serial Number..: 710KPCA0244667
>
> checking product...
> OKAY [  0.000s]
> sending 'boot_b' (40960 KB)...
> FAILED (data write failure (Protocol error))
> finished. total time: 0.162s
i have changed type-c cable to fastboot it,but it faile.
please tell me how to solve it..
thanks

**Comment by llllIIIllll** [comment]
I use Factory Images for Pixel Devices to fastboot ,it run success.
but i use compiled AOSP to fastboot,it run failed. i don't how to set configuration of AOSP.
you have same problem?

**Comment by nathanchance** [comment]
It's almost always a cable or port issue. Closing this issue as it is not directly related to this manifest.

**Comment by poooooooooooooi** [comment]
What kind of cable do I need ？i try different cable to fastboot。it failed ,could you tell me the specific version of the cable.
thanks.

**Comment by llllIIIllll** [comment]
it must be Macbook Pro to use type c -type c??
omg

**Comment by thinkycx** [comment]
> it must be Macbook Pro to use type c -type c??
> omg

Excuse me, could you tell me that which **AOSP branch and kernel msm branch** do you choose?
I have also compiled the AOSP 8.1.0_r12 and kernel msm android-msm-wahoo-4.4-oreo-m2 for pixel2 and it seems works well.

Thank you .
